### ISSUE TITLE
Apply multipart suggestions

### ISSUE THREAD

**Issue by estebank** [rust-lang-nursery/rustfix#152] opened 2018-11-26 22:10 UTC
Suggestions can perform multiple changes simultaneously (`err.multipart_suggestion[_with_applicability](message, vec![(span, code)])`). `rustfix` should be able to apply these.

CC https://github.com/rust-lang/rust/pull/56220.

**Comment by zackmdavis** [comment] 2018-11-27 01:21
duplicate of #141

**Closed** 2018-11-28 22:45 UTC
